[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "numpy>=2.2.3",
    "pytelegrambotapi>=4.26.0",
    "requests>=2.32.3",
    "yt-dlp>=2025.2.19",
]
